import { type Session } from "next-auth";
import { SessionProvider } from "next-auth/react";
import Head from "next/head";
import { type AppType } from "next/app";
import { GeistSans } from 'geist/font/sans';


import { api } from "@/utils/api";

import "@/styles/globals.css";
import { SideNav } from "@/components/SideNav";
import DiscoverSidebar from "@/components/DiscoverSidebar";

const MyApp: AppType<{ session: Session | null }> = ({
  Component,
  pageProps: { session, ...pageProps },
}) => {
  return (
    <SessionProvider session={session}>
      <Head>
        <title>T3 Twitter Clone</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`container mx-auto flex items-start ${GeistSans.className}`}>
        <SideNav />
        <div className="min-h-screen flex-grow border-x w-full max-w-2xl">
          <Component {...pageProps} />
        </div>
        <DiscoverSidebar />
      </div>
    </SessionProvider>
  );
};

export default api.withTRPC(MyApp);
